
MASTER_T = {
  machine_name: "master",
  hostname: "master",
  ip: "192.168.56.110",
  box: "debian/bookworm64"
}

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = MASTER_T[:box]
    master.vm.network "private_network", ip: MASTER_T[:ip]
    master.vm.hostname = MASTER_T[:hostname]
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = MASTER_T[:machine_name]
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "scripts/install.sh"
  config.vm.provision "shell", path: "scripts/setup.sh"
end