apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-server-tcp
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`) # This catches all traffic on the websecure port
    services:
    - name: argocd-server
      port: 443
  tls:
    passthrough: true
