apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/test-repo.git'
    path: .
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
