apiVersion: v1
kind: Secret
metadata:
  name: gitlab-test-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: https://gitlab.local/root/test-repo.git
  insecure: "true"
