global:
  edition: ce
  installCertmanager: false
  hosts:
    domain: 152.42.132.123.nip.io
  ingress:
    configureCertmanager: false
    class: "nginx"
  kas:
    enabled: false

nginx-ingress:
  enabled: false
prometheus:
  install: false
grafana:
  enabled: false
gitlab-runner:
  install: false
registry:
  enabled: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
  sidekiq:
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
  toolbox:
    enabled: false

postgresql:
  primary:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 400Mi
        cpu: 200m

redis:
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 200Mi
        cpu: 100m

