# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "debian/bookworm64"
    master.vm.hostname = "Server"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "serhouni"
      vb.gui = false
      vb.memory = "2048"
      vb.cpus = 2
    end
    master.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "ServerWorker"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/server_worker.sh"
  end
end
